import { Product, Category, Order } from '@/types'

export const categories: Category[] = [
  {
    id: '1',
    name: 'Descartáveis',
    slug: 'descartaveis',
    description: 'Vapes descartáveis prontos para uso',
    image: '/categories/descartaveis.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 1,
    created_at: '2024-01-01',
    product_count: 45,
  },
  {
    id: '2',
    name: 'Pods',
    slug: 'pods',
    description: 'Sistemas de pod recarregáveis',
    image: '/categories/pods.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 2,
    created_at: '2024-01-01',
    product_count: 32,
  },
  {
    id: '3',
    name: 'Juice / Líquidos',
    slug: 'juices',
    description: 'Líquidos e essências para vape',
    image: '/categories/juices.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 3,
    created_at: '2024-01-01',
    product_count: 78,
  },
  {
    id: '4',
    name: 'Kits',
    slug: 'kits',
    description: 'Kits completos para iniciantes e avançados',
    image: '/categories/kits.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 4,
    created_at: '2024-01-01',
    product_count: 18,
  },
  {
    id: '5',
    name: 'Acessórios',
    slug: 'acessorios',
    description: 'Acessórios e peças de reposição',
    image: '/categories/acessorios.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 5,
    created_at: '2024-01-01',
    product_count: 24,
  },
  {
    id: '6',
    name: 'Coils / Resistências',
    slug: 'coils',
    description: 'Resistências e coils para manutenção',
    image: '/categories/coils.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 6,
    created_at: '2024-01-01',
    product_count: 15,
  },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Ignite V80 - Blueberry Ice',
    slug: 'ignite-v80-blueberry-ice',
    description: 'O Ignite V80 é o descartável premium que combina design elegante com sabor intenso. Com 8000 puffs, bateria recarregável e o sabor refrescante de blueberry com gelo, é a escolha perfeita para quem busca qualidade e durabilidade.',
    short_description: 'Descartável premium com 8000 puffs e sabor blueberry ice',
    price: 89.90,
    compare_at_price: 129.90,
    cost_price: 35.00,
    sku: 'IGN-V80-BBI',
    barcode: null,
    stock_quantity: 150,
    low_stock_threshold: 20,
    category_id: '1',
    brand: 'Ignite',
    images: [
      'https://images.unsplash.com/photo-1560913210-de0287645665?w=600',
      'https://images.unsplash.com/photo-1559813514-a5f2f5fca397?w=600',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1560913210-de0287645665?w=400',
    is_active: true,
    is_featured: true,
    tags: ['descartável', 'ignite', 'blueberry', 'gelo'],
    nicotine_strength: '50mg',
    flavor: 'Blueberry Ice',
    puff_count: 8000,
    battery_capacity: '550mAh',
    volume: '16ml',
    weight: 60,
    dimensions: '10x3x2cm',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '2',
    name: 'Elfbar BC5000 - Watermelon Ice',
    slug: 'elfbar-bc5000-watermelon-ice',
    description: 'O Elf Bar BC5000 é um dos descartáveis mais populares do mercado. Design compacto, sabor watermelon ice refrescante e 5000 puffs de pura satisfação. Bateria recarregável via USB-C.',
    short_description: 'Descartável compacto com 5000 puffs sabor melancia gelada',
    price: 69.90,
    compare_at_price: 99.90,
    cost_price: 28.00,
    sku: 'ELF-BC5K-WMI',
    barcode: null,
    stock_quantity: 200,
    low_stock_threshold: 30,
    category_id: '1',
    brand: 'Elf Bar',
    images: [
      'https://images.unsplash.com/photo-1567922045116-2a00fae2ed03?w=600',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1567922045116-2a00fae2ed03?w=400',
    is_active: true,
    is_featured: true,
    tags: ['descartável', 'elfbar', 'melancia', 'gelo'],
    nicotine_strength: '50mg',
    flavor: 'Watermelon Ice',
    puff_count: 5000,
    battery_capacity: '650mAh',
    volume: '13ml',
    weight: 45,
    dimensions: '8x3x2cm',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '3',
    name: 'Lost Mary MO5000 - Grape Ice',
    slug: 'lost-mary-mo5000-grape-ice',
    description: 'Lost Mary MO5000 combina tecnologia mesh coil com design ergonômico. O sabor uva gelada é intenso e duradouro, oferecendo até 5000 puffs de experiência premium.',
    short_description: 'Mesh coil com 5000 puffs e sabor uva gelada',
    price: 74.90,
    compare_at_price: 109.90,
    cost_price: 30.00,
    sku: 'LM-MO5K-GRI',
    barcode: null,
    stock_quantity: 180,
    low_stock_threshold: 25,
    category_id: '1',
    brand: 'Lost Mary',
    images: [
      'https://images.unsplash.com/photo-1571266752354-3a02e4f89abf?w=600',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1571266752354-3a02e4f89abf?w=400',
    is_active: true,
    is_featured: true,
    tags: ['descartável', 'lost mary', 'uva', 'gelo'],
    nicotine_strength: '50mg',
    flavor: 'Grape Ice',
    puff_count: 5000,
    battery_capacity: '500mAh',
    volume: '13.5ml',
    weight: 50,
    dimensions: '9x3x2cm',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '4',
    name: 'Oxbar G8000 - Mango Ice',
    slug: 'oxbar-g8000-mango-ice',
    description: 'O Oxbar G8000 oferece performance excepcional com tela LED indicadora de bateria e líquido. 8000 puffs com sabor manga gelada, perfeito para o dia a dia.',
    short_description: 'Performance com tela LED e 8000 puffs sabor manga',
    price: 94.90,
    compare_at_price: 139.90,
    cost_price: 38.00,
    sku: 'OXB-G8K-MGI',
    barcode: null,
    stock_quantity: 120,
    low_stock_threshold: 15,
    category_id: '1',
    brand: 'Oxbar',
    images: [
      'https://images.unsplash.com/photo-1548174441-8ff5481ab62b?w=600',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1548174441-8ff5481ab62b?w=400',
    is_active: true,
    is_featured: true,
    tags: ['descartável', 'oxbar', 'manga', 'gelo', 'tela led'],
    nicotine_strength: '50mg',
    flavor: 'Mango Ice',
    puff_count: 8000,
    battery_capacity: '600mAh',
    volume: '16ml',
    weight: 65,
    dimensions: '11x3x2cm',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '5',
    name: 'SMOK Nord 5 Kit',
    slug: 'smok-nord-5-kit',
    description: 'O SMOK Nord 5 é o sistema de pod mais versátil do mercado. Com bateria de 2000mAh, potência ajustável e compatível com coils RPM 3, entrega sabor e vapor excepcionais.',
    short_description: 'Pod system versátil com 2000mAh e potência ajustável',
    price: 189.90,
    compare_at_price: 249.90,
    cost_price: 85.00,
    sku: 'SMK-NRD5-KIT',
    barcode: null,
    stock_quantity: 80,
    low_stock_threshold: 10,
    category_id: '2',
    brand: 'SMOK',
    images: [
      'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=600',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400',
    is_active: true,
    is_featured: true,
    tags: ['pod', 'smok', 'nord', 'kit', 'recarregável'],
    nicotine_strength: null,
    flavor: null,
    puff_count: null,
    battery_capacity: '2000mAh',
    volume: '5ml',
    weight: 120,
    dimensions: '12x4x2cm',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '6',
    name: 'Juice Zomo Mango Ice 30ml',
    slug: 'juice-zomo-mango-ice-30ml',
    description: 'O Juice Zomo Mango Ice traz o sabor tropical da manga combinado com um toque gelado refrescante. Formulado com alta qualidade para pod systems e vapes.',
    short_description: 'Juice premium sabor manga gelada 30ml',
    price: 44.90,
    compare_at_price: 59.90,
    cost_price: 15.00,
    sku: 'ZMO-MGI-30',
    barcode: null,
    stock_quantity: 300,
    low_stock_threshold: 50,
    category_id: '3',
    brand: 'Zomo',
    images: [
      'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400',
    is_active: true,
    is_featured: false,
    tags: ['juice', 'zomo', 'manga', 'gelo', '30ml'],
    nicotine_strength: '35mg',
    flavor: 'Mango Ice',
    puff_count: null,
    battery_capacity: null,
    volume: '30ml',
    weight: 50,
    dimensions: '8x3x3cm',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '7',
    name: 'Vaporesso XROS 3 Mini',
    slug: 'vaporesso-xros-3-mini',
    description: 'O Vaporesso XROS 3 Mini é compacto mas poderoso. Com tecnologia COREX e pods recarregáveis, oferece sabor premium em qualquer lugar. Bateria de 1000mAh e design ultra-portátil.',
    short_description: 'Pod ultra-compacto com tecnologia COREX',
    price: 159.90,
    compare_at_price: 199.90,
    cost_price: 72.00,
    sku: 'VPR-XR3M-KIT',
    barcode: null,
    stock_quantity: 95,
    low_stock_threshold: 15,
    category_id: '2',
    brand: 'Vaporesso',
    images: [
      'https://images.unsplash.com/photo-1560913210-de0287645665?w=600',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1560913210-de0287645665?w=400',
    is_active: true,
    is_featured: false,
    tags: ['pod', 'vaporesso', 'xros', 'compacto'],
    nicotine_strength: null,
    flavor: null,
    puff_count: null,
    battery_capacity: '1000mAh',
    volume: '2ml',
    weight: 40,
    dimensions: '7x2x1.5cm',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '8',
    name: 'RAZ TN9000 - Strawberry Banana',
    slug: 'raz-tn9000-strawberry-banana',
    description: 'RAZ TN9000 é o descartável de longa duração definitivo. Com 9000 puffs, tela indicadora e o delicioso sabor de morango com banana. Experiência premium do início ao fim.',
    short_description: 'Descartável 9000 puffs com sabor morango banana',
    price: 99.90,
    compare_at_price: 149.90,
    cost_price: 42.00,
    sku: 'RAZ-TN9K-STB',
    barcode: null,
    stock_quantity: 130,
    low_stock_threshold: 20,
    category_id: '1',
    brand: 'RAZ',
    images: [
      'https://images.unsplash.com/photo-1559813514-a5f2f5fca397?w=600',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1559813514-a5f2f5fca397?w=400',
    is_active: true,
    is_featured: true,
    tags: ['descartável', 'raz', 'morango', 'banana', '9000 puffs'],
    nicotine_strength: '50mg',
    flavor: 'Strawberry Banana',
    puff_count: 9000,
    battery_capacity: '650mAh',
    volume: '18ml',
    weight: 70,
    dimensions: '11x3x2cm',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
]

export const sampleOrders: Order[] = [
  {
    id: 'ORD-001',
    user_id: 'user-1',
    status: 'delivered',
    subtotal: 259.70,
    shipping_cost: 15.90,
    discount: 0,
    total: 275.60,
    payment_method: 'pix',
    payment_status: 'paid',
    payment_id: 'pay_123',
    shipping_method: 'sedex',
    tracking_code: 'BR123456789',
    notes: null,
    customer_name: 'João Silva',
    customer_email: 'joao@email.com',
    customer_phone: '11999887766',
    customer_cpf: '12345678901',
    shipping_address: {
      street: 'Rua das Flores',
      number: '123',
      complement: 'Apto 45',
      neighborhood: 'Centro',
      city: 'São Paulo',
      state: 'SP',
      zip_code: '01001000',
      country: 'BR',
    },
    billing_address: null,
    items: [
      {
        id: 'item-1',
        order_id: 'ORD-001',
        product_id: '1',
        product_name: 'Ignite V80 - Blueberry Ice',
        product_image: 'https://images.unsplash.com/photo-1560913210-de0287645665?w=400',
        quantity: 2,
        unit_price: 89.90,
        total_price: 179.80,
      },
      {
        id: 'item-2',
        order_id: 'ORD-001',
        product_id: '2',
        product_name: 'Elfbar BC5000 - Watermelon Ice',
        product_image: 'https://images.unsplash.com/photo-1567922045116-2a00fae2ed03?w=400',
        quantity: 1,
        unit_price: 69.90,
        total_price: 69.90,
      },
    ],
    created_at: '2024-03-15T10:30:00Z',
    updated_at: '2024-03-18T14:20:00Z',
  },
  {
    id: 'ORD-002',
    user_id: 'user-2',
    status: 'shipped',
    subtotal: 189.90,
    shipping_cost: 0,
    discount: 19.00,
    total: 170.90,
    payment_method: 'credit_card',
    payment_status: 'paid',
    payment_id: 'pay_456',
    shipping_method: 'pac',
    tracking_code: 'BR987654321',
    notes: 'Presente, por favor embalar',
    customer_name: 'Maria Santos',
    customer_email: 'maria@email.com',
    customer_phone: '21988776655',
    customer_cpf: '98765432101',
    shipping_address: {
      street: 'Av. Brasil',
      number: '456',
      complement: null,
      neighborhood: 'Copacabana',
      city: 'Rio de Janeiro',
      state: 'RJ',
      zip_code: '22041080',
      country: 'BR',
    },
    billing_address: null,
    items: [
      {
        id: 'item-3',
        order_id: 'ORD-002',
        product_id: '5',
        product_name: 'SMOK Nord 5 Kit',
        product_image: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400',
        quantity: 1,
        unit_price: 189.90,
        total_price: 189.90,
      },
    ],
    created_at: '2024-03-20T15:45:00Z',
    updated_at: '2024-03-22T09:15:00Z',
  },
  {
    id: 'ORD-003',
    user_id: null,
    status: 'pending',
    subtotal: 314.70,
    shipping_cost: 22.50,
    discount: 0,
    total: 337.20,
    payment_method: null,
    payment_status: 'pending',
    payment_id: null,
    shipping_method: 'sedex',
    tracking_code: null,
    notes: null,
    customer_name: 'Pedro Oliveira',
    customer_email: 'pedro@email.com',
    customer_phone: '31977665544',
    customer_cpf: '45678912301',
    shipping_address: {
      street: 'Rua Minas Gerais',
      number: '789',
      complement: 'Casa',
      neighborhood: 'Savassi',
      city: 'Belo Horizonte',
      state: 'MG',
      zip_code: '30130000',
      country: 'BR',
    },
    billing_address: null,
    items: [
      {
        id: 'item-4',
        order_id: 'ORD-003',
        product_id: '4',
        product_name: 'Oxbar G8000 - Mango Ice',
        product_image: 'https://images.unsplash.com/photo-1548174441-8ff5481ab62b?w=400',
        quantity: 2,
        unit_price: 94.90,
        total_price: 189.80,
      },
      {
        id: 'item-5',
        order_id: 'ORD-003',
        product_id: '3',
        product_name: 'Lost Mary MO5000 - Grape Ice',
        product_image: 'https://images.unsplash.com/photo-1571266752354-3a02e4f89abf?w=400',
        quantity: 1,
        unit_price: 74.90,
        total_price: 74.90,
      },
      {
        id: 'item-6',
        order_id: 'ORD-003',
        product_id: '6',
        product_name: 'Juice Zomo Mango Ice 30ml',
        product_image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400',
        quantity: 1,
        unit_price: 44.90,
        total_price: 44.90,
      },
    ],
    created_at: '2024-03-25T08:00:00Z',
    updated_at: '2024-03-25T08:00:00Z',
  },
]
